const initialProductsState = {
  allProducts: [
    {
      category: "food",
      name: "Dry Food",
      description: "5 lbs of dry food",
      price: "$24.99",
      inventory: 50,
      image:"https://www.purina.ca/sites/default/files/styles/kraken_product_carousel_regular/public/purina-one-cat-plus-indoor-advantage-dry-cat-food.png?itok=ntgSKwVS",
    },
    {
      category: "food",
      name: "Wet Food",
      description: "8oz Can of Chicken",
      price: "$1.29",
      inventory: 200,
      image: "https://image.chewy.com/is/image/catalog/91563_MAIN._AC_SL600_V1657661111_.jpg",
    },
    {
      category: "litter",
      name: "Litter",
      description: "3 lbs litter",
      price: "$19.99",
      inventory: 50,
      image: "https://assets.petco.com/petco/image/upload/f_auto,q_auto/3221386-center-1",
    },
    {
      category: "accessories",
      name: "Cat toys",
      description: "A faux mouse for your cat",
      price: "$1.99",
      inventory: 200,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrHLqRuBp_OLl8XdEB_LpcYOOpyanuji8BGqjiDe82iw&usqp=CAU&ec=48665699",
    },
    {
      category: "food",
      name: "Canned Tuna",
      description: "Tasty canned tuna for your cat",
      price: "$2.99",
      inventory: 100,
      image: "https://image.chewy.com/is/image/catalog/50673_MAIN._AC_SL600_V1642564589_.jpg",
    },
    {
      category: "food",
      name: "Salmon Treats",
      description: "Delicious salmon treats for your cat",
      price: "$3.99",
      inventory: 80,
      image: "https://image.chewy.com/is/image/catalog/250599_MAIN._AC_SL600_V1602266526_.jpg",
    },
    {
      category: "food",
      name: "Chicken Bites",
      description: "Crunchy chicken bites for your cat",
      price: "$2.49",
      inventory: 120,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4_mgKqzkJrFcAzt7NAnsFDfr0s2UIIfb0eVH5W8uczfbTLFsk",
    },
    {
      category: "litter",
      name: "Clumping Litter",
      description: "Premium clumping litter for easy cleanup",
      price: "$14.99",
      inventory: 60,
      image: "https://image.chewy.com/is/image/catalog/113555_MAIN._AC_SL600_V1676480672_.jpg",
    },
    {
      category: "litter",
      name: "Silica Crystal Litter",
      description: "Odor-absorbing silica crystal litter",
      price: "$19.99",
      inventory: 40,
      image: "https://image.chewy.com/is/image/catalog/194434_MAIN._AC_SL1200_V1583525960_.jpg",
    },
    {
      category: "litter",
      name: "Pine Pellet Litter",
      description: "Natural pine pellet litter for freshness",
      price: "$12.99",
      inventory: 80,
      image: "https://image.chewy.com/is/image/catalog/161458_MAIN._AC_SL1200_V1657656016_.jpg",
    },
    {
      category: "accessories",
      name: "Cat Scratching Post",
      description: "Durable cat scratching post for claw maintenance",
      price: "$29.99",
      inventory: 30,
      image: "https://image.chewy.com/is/image/catalog/261421_MAIN._AC_SL1200_V1606147612_.jpg",
    },
    {
      category: "accessories",
      name: "Interactive Feather Toy",
      description: "Entertaining interactive feather toy for playtime",
      price: "$6.99",
      inventory: 100,
      image: "https://image.chewy.com/is/image/catalog/137512_MAIN._AC_SL1200_V1575494384_.jpg",
    },
    {
      category: "accessories",
      name: "Cat Bed",
      description: "Cozy cat bed for a comfortable nap",
      price: "$19.99",
      inventory: 50,
      image: "https://image.chewy.com/is/image/catalog/193279_MAIN._AC_SL1200_V1631679136_.jpg",
    },
  ],
};

module.exports = initialProductsState;
